[deprecation]
showPyplotGlobalUse = false

[theme]
# https://blog.streamlit.io/introducing-theming/
#primaryColor="#d33682"
#backgroundColor="#002b36"
#secondaryBackgroundColor="#586e75"
#textColor="#fafafa"
#font="sans serif"

# TODO: Change app theme color
